version: "3"
services:

  db:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=somepassword

  web:
    build: .
    #command: bundle exec rackup -p 3000
    #command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -e production -p 3000 -b '0.0.0.0'"
    command: bash -c "rm -f tmp/pids/server.pid && rake db:create && rake db:migrate assets:precompile && puma -C config/puma.rb"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - POSTGRES_PASSWORD=somepassword
      - RAILS_ENV=production
    depends_on:
      - db